image: node:4.2.2


cache:
  paths:
    - node_modules/

production:
  before_script:
    - npm update --depth=0
  after_script:
    - cp -R ./public /home/sites/fogrew/fogrew.site/public
  script:
    - gulp build
  artifacts:
    paths:
    - public
  only:
    - master

# ci-trigger:
#   type: deploy
#   script:
#     - "curl -X POST -F token=60cb940fcca21fe5e15d109ef56bc1 -F ref=master http://git.jkoff.ru:8081/api/v3/projects/7/trigger/builds"
